# Generated by Django 5.2.15 on 2026-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Electricidad', 'Electricidad'), ('Gasfitería', 'Gasfitería'), ('Carpintería', 'Carpintería'), ('Cerrajería', 'Cerrajería'), ('Pintura', 'Pintura')], max_length=50)),
                ('oficio', models.CharField(max_length=150)),
                ('experiencia', models.CharField(choices=[('Menos de 1 año', 'Menos de 1 año'), ('1-3 años', '1-3 años'), ('3-5 años', '3-5 años'), ('Más de 5 años', 'Más de 5 años')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('calificacion_promedio', models.FloatField(default=0.0)),
                ('num_calificaciones', models.IntegerField(default=0)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
