# Generated by Django 5.2.15 on 2026-06-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_trabajadores/'),
        ),
    ]
