# Generated by Django 5.2.15 on 2026-08-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_trabajador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='categoria',
            field=models.CharField(choices=[('Electricidad', 'Electricidad'), ('Gasfitería', 'Gasfitería'), ('Carpintería', 'Carpintería'), ('Cerrajería', 'Cerrajería'), ('Pintura', 'Pintura'), ('Albañilería y Construcción', 'Albañilería y Construcción'), ('Drywall y Cielorraso', 'Drywall y Cielorraso'), ('Soldadura y Estructuras Metálicas', 'Soldadura y Estructuras Metálicas'), ('Reparación de Electrodomésticos', 'Reparación de Electrodomésticos'), ('Termas Solares y Calefacción', 'Termas Solares y Calefacción'), ('Refrigeración y Climatización', 'Refrigeración y Climatización'), ('Vidriería y Aluminios', 'Vidriería y Aluminios'), ('Jardinería y Áreas Verdes', 'Jardinería y Áreas Verdes'), ('Mantenimiento de Cómputo y Redes', 'Mantenimiento de Cómputo y Redes'), ('Limpieza y Desinfección', 'Limpieza y Desinfección'), ('Otro', 'Otro (Especialidad no listada)')], max_length=100),
        ),
    ]
