# Generated by Django 5.2.15 on 2026-08-31 22:51

import config.file_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_alter_trabajador_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=config.file_security.ruta_foto_trabajador_segura),
        ),
    ]
