# Generated by Django 5.2.15 on 2026-08-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='metodo_pago',
            field=models.CharField(blank=True, default='Efectivo', max_length=30),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='precio_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
