# Generated by Django 5.2.15 on 2026-08-28 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_solicitud_metodo_pago_solicitud_precio_acordado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('celular_contacto', models.CharField(max_length=15)),
                ('distrito', models.CharField(default='Wanchaq', max_length=100)),
                ('oficio_solicitado', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('asignado', 'Técnico asignado'), ('atendido', 'Atendido / Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('notas_admin', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos_oficio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
