# Generated by Django 5.2.15 on 2026-08-27 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('solicitud_nueva', 'Nueva Solicitud'), ('solicitud_aceptada', 'Solicitud Aceptada'), ('solicitud_en_progreso', 'Solicitud en Progreso'), ('solicitud_completada', 'Solicitud Completada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('calificacion_recibida', 'Calificación Recibida'), ('general', 'General')], default='general', max_length=30)),
                ('leida', models.BooleanField(default=False)),
                ('enlace', models.CharField(blank=True, default='/solicitudes', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
