# Generated by Django 5.2.15 on 2026-08-31 22:51

import config.file_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=config.file_security.ruta_foto_usuario_segura),
        ),
    ]
